---

- name: Make sure the apply_changes script is present on the system
  copy:
      src: "resources/apply_changes.sh"
      dest: "/usr/bin/apply_changes.sh"
      mode: 0755

- name: Update IPv4 CIDR and IPv6 prefix to random ranges
  command: "/usr/bin/vpn-server-api-update-ip --profile internet --host {{ \
  ansible_fqdn }}"
  args:
    creates: "/etc/vpn-server-api/config.php"

- name: Initialize CA
  command: "/usr/bin/vpn-server-api-init"
  become_user: www-data
  args:
    creates: "{{ serverapibasedir }}/data/db.sqlite"


- name: Make sure OpenVPN service is enabled
  service:
      name: openvpn
      state: started
      enabled: yes
  notify: openvpn

- name: Check if user db exists.
  stat:
      path: "{{ portalbasedir }}/data/db.sqlite"
  register: userdb

- name: Copy initial user db schema DDL
  copy:
      src: "resources/schema.sql"
      dest: "{{ portalbasedir }}/schema/{{ sqlite_schema_version }}.schema"

- name: Generate initial version data
  template:
      src: "templates/init.sql.j2"
      dest: "/tmp/version.sql"

- name: Create initial user db
  shell: >-
      sqlite3 {{ portalbasedir }}/data/db.sqlite -init {{ portalbasedir }}/schema/*.schema
  when: userdb.stat.exists == False
  become_user: "www-data"

- name: Set version data for user db
  shell: >-
      sqlite3 {{ portalbasedir }}/data/db.sqlite < /tmp/version.sql
  when: userdb.stat.exists == False
  become_user: "www-data"


- name: Have a place to add custom openvpn-server settings
  file:
    path: '/etc/systemd/system/openvpn-server@.service.d/'
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Override system openvpn-server max nproc
  copy:
    src: 'resources/openvpn-server.service-override.conf'
    dest: '/etc/systemd/system/openvpn-server@.service.d/override.conf'
  notify: systemd

- name: be sure we have source routing tables
  copy:
    src: 'resources/rt_tables'
    dest: '/etc/iproute2/rt_tables'

- name: be sure tun is loaded at boottime
  copy:
    src: 'resources/modules-tun.conf'
    dest: '/etc/modules-load.d/tun.conf'


- name: be sure IP forwarding is enabled
  copy:
    src: 'resources/forwarding.conf'
    dest: '/etc/sysctl.d/70-forwarding.conf'
  notify: sysctl

- name: add helper to create vpn services
  copy:
    src: 'resources/vpn-services-init'
    dest: '/usr/local/sbin/vpn-services-init'
    mode: 0755

- name: Add users
  import_tasks: users.yml
  when: deployment is defined and deployment == True

- name: Make sure apache is running with latest config
  service:
      name: apache2
      state: restarted
      enabled: yes

- name: Regenerate OpenVPN config
  command: "/usr/bin/vpn-server-node-server-config"
  notify: openvpn

- name: Generate/install firewall rules
  command: "/usr/bin/vpn-server-node-generate-firewall --install"
  notify: firewall

