---

- name: Copy keys to host
  copy:
    src: "config/{{ ansible_fqdn }}/ssl/{{ ansible_fqdn }}.key"
    dest: "{{ cert_location.key }}"

- name: Copy cert to host
  copy:
    src: "config/{{ ansible_fqdn }}/ssl/{{ ansible_fqdn }}.crt"
    dest: "{{ cert_location.cert }}"
  notify: apache
